//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solti.Utils.Proxy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solti.Utils.Proxy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interceptor can not be abstract..
        /// </summary>
        internal static string ABSTRACT_INTERCEPTOR {
            get {
                return ResourceManager.GetString("ABSTRACT_INTERCEPTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous match for member: {0}.
        /// </summary>
        internal static string AMBIGUOUS_MATCH {
            get {
                return ResourceManager.GetString("AMBIGUOUS_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation failed. See &quot;Data&quot; for details..
        /// </summary>
        internal static string COMPILATION_FAILED {
            get {
                return ResourceManager.GetString("COMPILATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic assemblies are not supported..
        /// </summary>
        internal static string DYNAMIC_ASM {
            get {
                return ResourceManager.GetString("DYNAMIC_ASM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A generator can not be generic..
        /// </summary>
        internal static string GENERIC_GENERATOR {
            get {
                return ResourceManager.GetString("GENERIC_GENERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target interface can not be generic.
        /// </summary>
        internal static string GENERIC_IFACE {
            get {
                return ResourceManager.GetString("GENERIC_IFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method (&quot;{0}&quot;) is internal. The declaring assembly should be annotated with the InternalsVisibleToAttribute(&quot;{1}&quot;)..
        /// </summary>
        internal static string IVT_REQUIRED {
            get {
                return ResourceManager.GetString("IVT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method (&quot;{0}&quot;) is not visible..
        /// </summary>
        internal static string METHOD_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("METHOD_NOT_VISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target does not implement the member: {0}.
        /// </summary>
        internal static string MISSING_IMPLEMENTATION {
            get {
                return ResourceManager.GetString("MISSING_IMPLEMENTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one public constructor should be declared on {0}..
        /// </summary>
        internal static string NO_PUBLIC_CTOR {
            get {
                return ResourceManager.GetString("NO_PUBLIC_CTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be a class..
        /// </summary>
        internal static string NOT_A_CLASS {
            get {
                return ResourceManager.GetString("NOT_A_CLASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter must be a TypeGenerator descendant..
        /// </summary>
        internal static string NOT_A_GENERATOR {
            get {
                return ResourceManager.GetString("NOT_A_GENERATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be a InterfaceInterceptor descendant..
        /// </summary>
        internal static string NOT_AN_INTERCEPTOR {
            get {
                return ResourceManager.GetString("NOT_AN_INTERCEPTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be an interface..
        /// </summary>
        internal static string NOT_AN_INTERFACE {
            get {
                return ResourceManager.GetString("NOT_AN_INTERFACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target is NULL..
        /// </summary>
        internal static string NULL_TARGET {
            get {
                return ResourceManager.GetString("NULL_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference return values are not supported..
        /// </summary>
        internal static string REF_RETURNS_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("REF_RETURNS_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interceptor can not be sealed..
        /// </summary>
        internal static string SEALED_INTERCEPTOR {
            get {
                return ResourceManager.GetString("SEALED_INTERCEPTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &quot;{0}&quot; can not be found..
        /// </summary>
        internal static string TYPE_NOT_FOUND {
            get {
                return ResourceManager.GetString("TYPE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (or its enclosing type) is not visible. The declaring assembly should be annotated with the InternalsVisibleToAttribute(&quot;{1}&quot;)..
        /// </summary>
        internal static string TYPE_NOT_VISIBLE {
            get {
                return ResourceManager.GetString("TYPE_NOT_VISIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access modifier could not be determined..
        /// </summary>
        internal static string UNDETERMINED_ACCESS_MODIFIER {
            get {
                return ResourceManager.GetString("UNDETERMINED_ACCESS_MODIFIER", resourceCulture);
            }
        }
    }
}
